name: CI

on:
  push:
    branches:
    - "master"

jobs:
  github-pages:
    name: Github Pages
    runs-on: ubuntu-22.04
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Check out source repository
        uses: actions/checkout@v2

      - uses: darklab8/fl-configs/.github/actions/checkout-freelancer@master
        with:
          freelancer-mod: "discovery"
          freelancer-folder: ${{ github.workspace }}/fl-data
          ssh-key-base64-discovery: ${{ secrets.ID_RSA_FILES_FREELANCER_DISCOVERY }}

      - run: ls ./fl-data
  
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
            go-version: 1.21

      - name: Install Task
        run: |
            sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b /usr/local/bin

      - name: Install templ
        run: go install github.com/a-h/templ/cmd/templ@v0.2.747
      
      - name: Build templ file to go
        run: templ generate

      - name: Add versions
        run: task build-version
          
      # no point to do that
      # - name: Patch to latest
      #   run: go run ${{ github.workspace }}/main.go patch 
      #   working-directory: ${{ github.workspace }}/fl-data

      - name: Test things
        run: task test -- -v
        env:
          DARKMAP_LOG_LEVEL: "DEBUG"

      - name: build
        run: task build
        env:
            SITE_ROOT: "/fl-darkmap/"
            FREELANCER_FOLDER: ${{ github.workspace }}/fl-data

      - uses: actions/upload-pages-artifact@v1
        with:
            name: github-pages
            path: ./build

      - name: Deploy to pages
        uses: actions/deploy-pages@v1
        id: deployment
